[package]
name = "hacamegui-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
hacam-lib-rs = "0.1.0"
wgpu = "25.0.2" # wgpu@26 won't compile if there's wgpu@25 in the tree 
bytemuck = { version = "1.14", features = ["derive"] }
glam = "0.30.5"
anyhow = "1.0.98"
tokio = { version = "1.47.1", features = ["full"] }
futures = "0.3.31"
lovely_env_logger = "0.6.2"
eframe = { version = "0.32.0", features = ["wgpu"] }
mimalloc = "0.1.47"
chrono = "0.4.41"
log = "0.4.27"
int-enum = "1.2.0"
yuv = "0.8.6"
openh264 = "0.8.1"
minimp4 = "0.1.2"
rfd = "0.15.4"
image = { version = "0.25.8", features = ["jpeg"] }
mp4-atom = "0.8.1"
uuid = { version = "1.18.1", features = ["v4"] }
indoc = "2.0.6"

[profile.release]
debug = true
